#line 2 "def.l.cc"

#line 4 "def.l.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer def__create_buffer
#define yy_delete_buffer def__delete_buffer
#define yy_flex_debug def__flex_debug
#define yy_init_buffer def__init_buffer
#define yy_flush_buffer def__flush_buffer
#define yy_load_buffer_state def__load_buffer_state
#define yy_switch_to_buffer def__switch_to_buffer
#define yyin def_in
#define yyleng def_leng
#define yylex def_lex
#define yylineno def_lineno
#define yyout def_out
#define yyrestart def_restart
#define yytext def_text
#define yywrap def_wrap
#define yyalloc def_alloc
#define yyrealloc def_realloc
#define yyfree def_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE def_restart(def_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t def_leng;

extern FILE *def_in, *def_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up def_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up def_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via def_restart()), so that the user can continue scanning by
	 * just pointing def_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when def_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t def_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow def_wrap()'s to do buffer switches
 * instead of setting up a fresh def_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void def_restart (FILE *input_file  );
void def__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE def__create_buffer (FILE *file,int size  );
void def__delete_buffer (YY_BUFFER_STATE b  );
void def__flush_buffer (YY_BUFFER_STATE b  );
void def_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void def_pop_buffer_state (void );

static void def_ensure_buffer_stack (void );
static void def__load_buffer_state (void );
static void def__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER def__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE def__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE def__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE def__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *def_alloc (yy_size_t  );
void *def_realloc (void *,yy_size_t  );
void def_free (void *  );

#define yy_new_buffer def__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        def_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            def__create_buffer(def_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        def_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            def__create_buffer(def_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define def_wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *def_in = (FILE *) 0, *def_out = (FILE *) 0;

typedef int yy_state_type;

extern int def_lineno;

int def_lineno = 1;

extern char *def_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr def_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up def_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	def_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[218] =
    {   0,
        0,    0,   45,   43,    1,   42,   35,   35,   36,   40,
       36,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,    2,   40,
        0,   40,   41,   41,   41,   41,   41,   41,   34,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   33,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,    2,    0,   39,    0,   41,   41,   41,   41,   41,
       41,   31,   41,   41,   41,   41,   41,   41,   41,   30,
       41,   32,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,    0,   38,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   41,   28,
       41,   41,   29,   41,   41,   41,   26,   41,   41,   27,
       41,   41,   41,   41,    0,   41,   41,   41,   41,   41,
       41,   18,   23,   22,   24,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   25,   41,   37,   41,
       41,   19,   41,   41,   41,   41,   41,   41,   21,   17,
       41,   41,   16,   41,   20,   41,   41,   41,   41,   12,
       41,   41,   13,   41,   41,   15,   41,   41,   41,   14,
       41,   41,   10,   41,   41,   41,    9,   41,   11,   41,
       41,   41,   41,   41,   41,   41,    8,   41,   41,   41,

       41,    6,    5,   41,   41,    7,   41,   41,   41,   41,
       41,    4,   41,   41,   41,    3,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    4,
        4,    4,    4,    1,    6,    7,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    4,   10,
        1,   10,    1,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       20,   27,   28,   29,   30,   31,   32,   33,   34,   20,
       10,    8,   10,    1,   20,    1,   20,   20,   20,   20,

       35,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[36] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3
    } ;

static yyconst flex_uint16_t yy_base[220] =
    {   0,
        0,  423,  427,  429,  429,  429,  429,  417,  429,   29,
      418,  417,   30,   32,   33,   35,   34,   37,   36,   43,
       56,   49,   47,   61,   63,   48,   70,   73,    0,   75,
      414,   76,  415,   39,   71,   80,   84,   86,  414,   83,
       88,   93,   89,   91,   99,   95,  101,  100,  413,  102,
      106,  121,   98,  108,  122,  119,  127,  129,  132,  131,
      130,    0,  413,  131,  409,  134,  138,  140,  141,  146,
      148,  410,  147,  149,  151,  153,  156,  154,  158,  409,
      163,  408,  164,  165,  167,  166,  169,  175,  177,  178,
      171,  181,  180,  182,  185,  408,  404,  191,  189,  192,

      194,  196,  198,  208,  195,  209,  210,  211,  212,  405,
      213,  216,  404,  218,  222,  219,  403,  220,  223,  402,
      224,  225,  234,  236,  399,  237,  240,  241,  242,  243,
      244,  400,  399,  398,  397,  245,  261,  254,  246,  249,
      251,  253,  264,  266,  265,  272,  396,  274,  393,  275,
      277,  394,  278,  283,  279,  280,  284,  287,  393,  392,
      290,  293,  391,  294,  390,  295,  296,  297,  302,  389,
      298,  304,  388,  300,  303,  387,  305,  311,  312,  386,
      314,  316,  384,  322,  323,  324,  381,  327,  380,  325,
      329,  330,  336,  337,  340,  342,  378,  341,  343,  344,

      346,  376,  375,  348,  347,  358,  352,  353,  354,  369,
      349,  356,  360,  355,  374,   44,  429,   46,  389
    } ;

static yyconst flex_int16_t yy_def[220] =
    {   0,
      217,    1,  217,  217,  217,  217,  217,  217,  217,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  219,  217,
      217,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  219,  217,  217,  217,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  217,  217,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  217,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  217,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,    0,  217,  217
    } ;

static yyconst flex_uint16_t yy_nxt[465] =
    {   0,
        4,    5,    6,    7,    4,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   12,   12,   18,   12,
       12,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   12,   12,   12,   12,   31,  217,   32,  217,  217,
      217,  217,  217,  217,   65,  217,   43,   37,   33,  217,
      217,   38,   41,  217,  217,  217,   36,   39,   40,   35,
       42,   44,  217,   34,   48,   51,   45,  217,   52,  217,
       46,   53,   49,   54,   59,   55,  217,  217,   50,  217,
       47,   31,   31,   30,   32,   56,  217,   61,   57,  217,
      217,   58,  217,   60,  217,  217,   72,  217,   66,  217,

       69,  217,   67,   77,  217,  217,  217,  217,  217,   63,
       34,   68,  217,   70,  217,   82,   71,   74,   75,   86,
       73,   78,   76,   79,   81,  217,   80,  217,  217,   84,
       83,   85,   87,  217,   88,  217,  217,  217,  217,   64,
      217,   90,   92,   91,  217,   98,  217,  217,   89,   94,
       93,  101,  217,  217,  217,  217,   95,  217,  100,  217,
      217,  104,  217,   99,  217,   96,  103,  107,  109,  217,
      217,  217,  217,  217,  102,  217,  111,  217,  105,  114,
      106,  217,  108,  217,  217,  110,  217,  217,  217,  112,
      119,  217,  113,  121,  116,  217,  120,  217,  217,  115,

      217,  217,  217,  117,  217,  118,  130,  122,  128,  126,
      123,  131,  124,  127,  217,  217,  217,  217,  217,  217,
      129,  132,  217,  133,  217,  217,  217,  138,  217,  217,
      217,  217,  140,  142,  143,  136,  135,  134,  141,  137,
      217,  144,  217,  217,  145,  139,  217,  217,  217,  217,
      217,  217,  217,  146,  148,  217,  153,  217,  155,  217,
      217,  147,  160,  151,  152,  150,  154,  217,  156,  158,
      217,  217,  217,  157,  159,  161,  164,  163,  217,  162,
      217,  217,  166,  217,  217,  217,  217,  168,  170,  217,
      217,  169,  165,  217,  174,  171,  217,  175,  167,  217,

      217,  217,  217,  217,  217,  172,  217,  173,  217,  217,
      217,  217,  183,  176,  181,  178,  184,  217,  217,  180,
      217,  177,  217,  179,  190,  182,  189,  185,  217,  217,
      217,  217,  186,  217,  188,  217,  217,  193,  187,  192,
      198,  195,  217,  217,  191,  194,  217,  217,  217,  217,
      217,  196,  217,  217,  217,  217,  197,  204,  217,  217,
      217,  217,  217,  199,  217,  200,  217,  203,  201,  202,
      205,  207,  211,  206,  210,  217,  208,  213,  214,  209,
      217,  217,  217,  212,  217,  215,  217,  217,  216,   62,
      217,   62,  217,  217,  217,  217,  217,  217,  217,  217,

      217,  149,  217,  217,  217,  217,  217,  149,  217,  217,
      217,  217,   97,  125,  217,  217,  217,   97,   65,  217,
      217,  217,   64,  217,  217,   30,  217,   29,    3,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217
    } ;

static yyconst flex_int16_t yy_chk[465] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   10,   13,   10,   14,   15,
       17,   16,   19,   18,   34,   34,   19,   15,  218,   20,
      216,   15,   17,   23,   26,   22,   14,   15,   16,   13,
       18,   20,   21,   10,   22,   23,   21,   24,   23,   25,
       21,   23,   22,   23,   26,   24,   27,   35,   22,   28,
       21,   30,   32,   30,   32,   24,   36,   28,   25,   40,
       37,   25,   38,   27,   41,   43,   40,   44,   35,   42,

       38,   46,   36,   44,   53,   45,   48,   47,   50,   30,
       32,   37,   51,   38,   54,   48,   38,   42,   42,   53,
       41,   45,   43,   46,   47,   56,   46,   52,   55,   51,
       50,   52,   54,   57,   55,   58,   61,   60,   59,   64,
       66,   57,   59,   58,   67,   66,   68,   69,   56,   60,
       59,   69,   70,   73,   71,   74,   61,   75,   68,   76,
       78,   73,   77,   67,   79,   64,   71,   76,   78,   81,
       83,   84,   86,   85,   70,   87,   81,   91,   74,   85,
       75,   88,   77,   89,   90,   79,   93,   92,   94,   83,
       90,   95,   84,   92,   87,   99,   91,   98,  100,   86,

      101,  105,  102,   88,  103,   89,  102,   93,  100,   98,
       94,  103,   95,   99,  104,  106,  107,  108,  109,  111,
      101,  104,  112,  105,  114,  116,  118,  111,  115,  119,
      121,  122,  114,  116,  118,  108,  107,  106,  115,  109,
      123,  119,  124,  126,  121,  112,  127,  128,  129,  130,
      131,  136,  139,  122,  124,  140,  129,  141,  131,  142,
      138,  123,  140,  127,  128,  126,  130,  137,  136,  138,
      143,  145,  144,  137,  139,  141,  144,  143,  146,  142,
      148,  150,  146,  151,  153,  155,  156,  150,  153,  154,
      157,  151,  145,  158,  157,  154,  161,  158,  148,  162,

      164,  166,  167,  168,  171,  155,  174,  156,  169,  175,
      172,  177,  171,  161,  168,  164,  172,  178,  179,  167,
      181,  162,  182,  166,  181,  169,  179,  174,  184,  185,
      186,  190,  175,  188,  178,  191,  192,  185,  177,  184,
      192,  188,  193,  194,  182,  186,  195,  198,  196,  199,
      200,  190,  201,  205,  204,  211,  191,  199,  207,  208,
      209,  214,  212,  193,  206,  194,  213,  198,  195,  196,
      200,  204,  209,  201,  208,  210,  205,  211,  213,  207,
      215,  203,  202,  210,  197,  214,  189,  187,  215,  219,
      183,  219,  180,  176,  173,  170,  165,  163,  160,  159,

      152,  149,  147,  135,  134,  133,  132,  125,  120,  117,
      113,  110,   97,   96,   82,   80,   72,   65,   63,   49,
       39,   33,   31,   12,   11,    8,    3,    2,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int def__flex_debug;
int def__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *def_text;
#line 1 "def.l"
#line 2 "def.l"
#include <cstdio>
#include <iostream>
using namespace std;
#define YY_DECL extern "C" int def_lex()
#include "def.y.hh"
int def_line_number = 1;
#line 667 "def.l.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int def_lex_destroy (void );

int def_get_debug (void );

void def_set_debug (int debug_flag  );

YY_EXTRA_TYPE def_get_extra (void );

void def_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *def_get_in (void );

void def_set_in  (FILE * _in_str  );

FILE *def_get_out (void );

void def_set_out  (FILE * _out_str  );

yy_size_t def_get_leng (void );

char *def_get_text (void );

int def_get_lineno (void );

void def_set_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int def_wrap (void );
#else
extern int def_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( def_text, def_leng, 1, def_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( def_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( def_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, def_in))==0 && ferror(def_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(def_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int def_lex (void);

#define YY_DECL int def_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after def_text and def_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( def_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(def_text[def_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! def_in )
			def_in = stdin;

		if ( ! def_out )
			def_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			def_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				def__create_buffer(def_in,YY_BUF_SIZE );
		}

		def__load_buffer_state( );
		}

	{
#line 12 "def.l"


#line 891 "def.l.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of def_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 218 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 429 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 14 "def.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "def.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 16 "def.l"
{ return NAMESCASESENSITIVE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 17 "def.l"
{ return NONDEFAULTRULE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "def.l"
{ return DIVIDERCHAR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "def.l"
{ return BUSBITCHARS; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 20 "def.l"
{ return SPECIALNETS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 21 "def.l"
{ return COMPONENTS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 22 "def.l"
{ return PROPERTY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 23 "def.l"
{ return DISTANCE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "def.l"
{ return TRISTATE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "def.l"
{ return DIEAREA; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "def.l"
{ return MICRONS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "def.l"
{ return VERSION; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "def.l"
{ return POLYGON; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "def.l"
{ return ROUTED; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "def.l"
{ return PLACED; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "def.l"
{ return FIXED; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "def.l"
{ return DESIGN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "def.l"
{ return TRACKS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "def.l"
{ return OUTPUT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "def.l"
{ return INPUT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "def.l"
{ return INOUT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "def.l"
{ return LAYER; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "def.l"
{ return UNITS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "def.l"
{ return RECT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "def.l"
{ return STEP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "def.l"
{ return NETS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 42 "def.l"
{ return PINS; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "def.l"
{ return NEW; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 44 "def.l"
{ return END; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "def.l"
{ return OFF; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "def.l"
{ return ON; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "def.l"
{ return DO; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "def.l"
{ return def_text[0]; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "def.l"
{ def_lval.cval = def_text[0]; return CHAR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 52 "def.l"
{ def_lval.fval = atof(def_text); return NUMBER; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 53 "def.l"
{ def_lval.fval = atof(def_text); return NUMBER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "def.l"
{ def_lval.fval = atof(def_text); return NUMBER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "def.l"
{ def_lval.fval = atof(def_text); return NUMBER; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 57 "def.l"
{ def_lval.sval = strdup(def_text); return STRING; }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 59 "def.l"
{ def_line_number++; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 60 "def.l"
;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "def.l"
ECHO;
	YY_BREAK
#line 1170 "def.l.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed def_in at a new source and called
			 * def_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = def_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( def_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * def_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of def_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					def_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			def_restart(def_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) def_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 218 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 218 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 217);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up def_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					def_restart(def_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( def_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve def_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void def_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        def_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            def__create_buffer(def_in,YY_BUF_SIZE );
	}

	def__init_buffer(YY_CURRENT_BUFFER,input_file );
	def__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void def__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		def_pop_buffer_state();
	 *		def_push_buffer_state(new_buffer);
     */
	def_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	def__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (def_wrap()) processing, but the only time this flag
	 * is looked at is after def_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void def__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	def_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE def__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) def_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in def__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) def_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in def__create_buffer()" );

	b->yy_is_our_buffer = 1;

	def__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with def__create_buffer()
 * 
 */
    void def__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		def_free((void *) b->yy_ch_buf  );

	def_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a def_restart() or at EOF.
 */
    static void def__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	def__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then def__init_buffer was _probably_
     * called from def_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void def__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		def__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void def_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	def_ensure_buffer_stack();

	/* This block is copied from def__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from def__switch_to_buffer. */
	def__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void def_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	def__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		def__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void def_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)def_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in def_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)def_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in def_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE def__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) def_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in def__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	def__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to def_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       def__scan_bytes() instead.
 */
YY_BUFFER_STATE def__scan_string (yyconst char * yystr )
{
    
	return def__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to def_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE def__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) def_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in def__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = def__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in def__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up def_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		def_text[def_leng] = (yy_hold_char); \
		(yy_c_buf_p) = def_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		def_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int def_get_lineno  (void)
{
        
    return def_lineno;
}

/** Get the input stream.
 * 
 */
FILE *def_get_in  (void)
{
        return def_in;
}

/** Get the output stream.
 * 
 */
FILE *def_get_out  (void)
{
        return def_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t def_get_leng  (void)
{
        return def_leng;
}

/** Get the current token.
 * 
 */

char *def_get_text  (void)
{
        return def_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void def_set_lineno (int  _line_number )
{
    
    def_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see def__switch_to_buffer
 */
void def_set_in (FILE *  _in_str )
{
        def_in = _in_str ;
}

void def_set_out (FILE *  _out_str )
{
        def_out = _out_str ;
}

int def_get_debug  (void)
{
        return def__flex_debug;
}

void def_set_debug (int  _bdebug )
{
        def__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from def_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    def_in = stdin;
    def_out = stdout;
#else
    def_in = (FILE *) 0;
    def_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * def_lex_init()
     */
    return 0;
}

/* def_lex_destroy is for both reentrant and non-reentrant scanners. */
int def_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		def__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		def_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	def_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * def_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *def_alloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *def_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void def_free (void * ptr )
{
			free( (char *) ptr );	/* see def_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 62 "def.l"



